import os
import sys
from PySide6.QtCore import QThread, Signal

# Ensure CorridorKey/System is in path for imports
CURRENT_DIR = os.path.dirname(__file__)
SYSTEM_DIR = os.path.join(CURRENT_DIR, "System")
if SYSTEM_DIR not in sys.path:
    sys.path.append(SYSTEM_DIR)

# Deferred import to prevent main thread freeze
# from clip_manager import ClipAsset, ClipEntry, InferenceSettings, run_inference, run_birefnet

from utvfx.bridge.base_worker import BaseWorker

class CorridorKeyWorker(BaseWorker):
    def __init__(self, node_id, params, inputs, cache_dir, output_dir, parent=None):
        super().__init__(node_id, params, inputs, cache_dir, output_dir, parent)
        self.video_path = inputs.get("Video Plate")
        self.mask_path = inputs.get("Alpha Matte")


    def _get_asset_type(self, path):
        if os.path.isdir(path):
            return "sequence"
        ext = os.path.splitext(path)[1].lower()
        if ext in ['.mp4', '.mov', '.avi', '.mkv']:
            return "video"
        return "sequence"

    def run_task(self):
        from clip_manager import ClipAsset, ClipEntry, InferenceSettings, run_inference, run_birefnet
        import logging
        
        # Setup logging to route to UI
        class UISignalHandler(logging.Handler):
            def __init__(self, worker):
                super().__init__()
                self.worker = worker
            def emit(self, record):
                msg = self.format(record)
                self.worker.log_message.emit(self.worker.node_id, msg)
        
        ui_handler = UISignalHandler(self)
        ui_handler.setFormatter(logging.Formatter('%(message)s'))
        ui_handler.setLevel(logging.INFO)
        
        # Add to root logger to capture all module logs
        root_logger = logging.getLogger()
        root_logger.setLevel(logging.INFO)
        root_logger.addHandler(ui_handler)

        if not self.video_path or not os.path.exists(self.video_path):
            raise FileNotFoundError("Video path is invalid or missing.")

        self.log_message.emit(self.node_id, "Initializing CorridorKey pipeline...")
        
        # Intelligent Routing: Prefer JPG directory if it exists and was generated by Media Plate
        active_video_path = self.video_path
        if active_video_path and os.path.isdir(active_video_path) and os.path.basename(active_video_path) == "Video Plate":
            potential_jpg_dir = active_video_path + " JPG"
            if os.path.isdir(potential_jpg_dir):
                self.log_message.emit(self.node_id, "Intelligently routing to pre-rendered Media Plate JPEGs for CorridorKey...")
                active_video_path = potential_jpg_dir
                
        # 1. Create a dummy ClipEntry mapping to our node's cache directory
        clip = ClipEntry("NodeExecution", self.cache_dir)
        clip.input_asset = ClipAsset(active_video_path, self._get_asset_type(active_video_path))
        
        # Callbacks for progress tracking
        def on_frame(current, total):
            if self.is_cancelled:
                raise InterruptedError("Execution cancelled by user.")
            # clip_manager emits current frame, we update UI
            self.progress_update.emit(self.node_id, current, total)
            
        def on_start(name, total):
            self.log_message.emit(self.node_id, f"Processing {name}: {total} frames")

        # 2. Check for mask or generate Auto-Matte
        if self.mask_path and os.path.exists(self.mask_path):
            clip.alpha_asset = ClipAsset(self.mask_path, self._get_asset_type(self.mask_path))
        else:
            self.log_message.emit(self.node_id, "No mask provided. Generating auto-matte using BiRefNet...")
            # run_birefnet automatically writes to clip.root_path / "AlphaHint"
            run_birefnet(
                [clip],
                device=None,
                usage="General",
                dilate_radius=0,
                on_clip_start=on_start,
                on_frame_complete=on_frame
            )
            
            # Check if generation succeeded
            alpha_dir = os.path.join(self.cache_dir, "AlphaHint")
            if not os.path.exists(alpha_dir) or not os.listdir(alpha_dir):
                raise RuntimeError("BiRefNet auto-matte generation failed.")
                
            clip.alpha_asset = ClipAsset(alpha_dir, "sequence")

        # 3. Setup settings
        settings = InferenceSettings(
            input_is_linear=self.params.get("input_linear", False),
            despill_strength=float(self.params.get("despill_strength", 0.5)),
            auto_despeckle=self.params.get("clean_islands", True),
            despeckle_size=int(self.params.get("despeckle_thresh", 400)),
            refiner_scale=float(self.params.get("detail_intensity", 1.0)),
            generate_comp=True,
            gpu_post_processing=False,
            image_size=int(self.params.get("proc_res", 2048)),
            screen_color=self.params.get("screen_color", "green")
        )

        # 4. Run Inference
        self.log_message.emit(self.node_id, "Running CorridorKey core inference...")
        run_inference(
            [clip],
            device=None,
            backend="torch",
            settings=settings,
            on_clip_start=on_start,
            on_frame_complete=on_frame
        )
        
        self.log_message.emit(self.node_id, "CorridorKey pipeline complete.")
